services:
  backend:
    build:
      context: ./smart-api
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./smart-api:/app
    restart: always

  frontend:
    build:
      context: ./smart-zhkh
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./smart-zhkh:/app
    restart: unless-stopped

  auth-api:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8082:8082"
    volumes:
      - ./auth-api/:/app
    restart: always