services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak              
      POSTGRES_USER: lait              
      POSTGRES_PASSWORD: 123            
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --http-port 9080

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak 
      KC_DB_USERNAME: lait
      KC_DB_PASSWORD: 123

      KEYCLOAK_IMPORT: /opt/keycloak/data/import/smart-hcs.json

    volumes:
      - ./smart-hcs.json:/opt/keycloak/data/import/smart-hcs.json

    ports:
      - '9080:9080'
    depends_on:
      - db

volumes:
  keycloak_db:
